# Generated by Django 3.2.7 on 2022-08-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(max_length=12, unique=True)),
                ('note', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
