# Generated by Django 3.2.7 on 2022-08-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dress_Fit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupform',
            old_name='mobile',
            new_name='Grade',
        ),
        migrations.AddField(
            model_name='signupform',
            name='student_index',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
