# Generated by Django 3.2.7 on 2022-08-18 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dress_Fit', '0002_auto_20220818_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupform',
            old_name='Grade',
            new_name='S_Grade',
        ),
    ]
