# Generated by Django 3.2.7 on 2022-08-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dress_Fit', '0003_rename_grade_signupform_s_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupform',
            old_name='student_index',
            new_name='studentindex',
        ),
        migrations.RemoveField(
            model_name='signupform',
            name='S_Grade',
        ),
        migrations.RemoveField(
            model_name='signupform',
            name='note',
        ),
        migrations.AddField(
            model_name='signupform',
            name='SGrade',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='signupform',
            name='SPassword',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signupform',
            name='SUserName',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
