# Generated by Django 3.2.7 on 2022-08-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dress_Fit', '0004_auto_20220818_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video_ActivityID', models.CharField(max_length=100)),
                ('SubjectName', models.CharField(max_length=100)),
                ('PerformanceRange', models.CharField(blank=True, max_length=100)),
                ('Video_URL', models.CharField(blank=True, max_length=12)),
            ],
        ),
    ]
