# Generated by Django 3.2.7 on 2022-08-23 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dress_Fit', '0005_video_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_activity',
            name='Video_URL',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
