# Generated by Django 3.2.7 on 2022-10-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dress_Fit', '0007_auto_20220823_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=25)),
                ('Password', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='SignUpForm',
        ),
        migrations.DeleteModel(
            name='Video_Activity',
        ),
    ]
