# Generated by Django 3.2.7 on 2022-11-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dress_Fit', '0008_auto_20221024_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_UserName', models.CharField(max_length=25)),
                ('feedback_info', models.CharField(max_length=100)),
            ],
        ),
    ]
